### ISSUE TITLE
Withdraw TO Paypal

### ISSUE THREAD

**Issue by mahuaroy** [vincentchacha/e-wallet#2]
Dear Sir,

Withdraw to Paypal is not working. Can you give me some basic information for this so that I can try this to complete.

Regards.

**Comment by vincentchacha** [comment]
Hi, I did not implemented the feature of withdraw to paypal on the code.

**Comment by blorieju** [comment]
Hello Sir,

I would like to ask, where can I setup the configuration on PayPal? I'm interested to test your application :)
I can't find it on .env parameters to put my sandbox details and also I would like to include this functionality withdraw to paypal. Do you also have send money functionality directly to credit card?

**Comment by vincentchacha** [comment]
Hello @blorieju you can set up paypal details on the config/paypal.php file and set them up.
The send money functionality is not included, but if you need the functionality you can drop me an email.
