### ISSUE TITLE
Hi, there seems to be some files missing...

### ISSUE THREAD

**Issue by SoveringCoin** [vincentchacha/e-wallet#7]
Hi, there seems to be some files missing...
public/vendor/autoload.php

Please can you tell me if there are any files missing?

thanks for your project, I hope I can set it up.

**Comment by vincentchacha** [comment]
Hi, 
Ensure that you run the following command in the project root directory :-
      composer install

This will install the vendor directory with all the dependencies listed on composer.json fils
